const mockProducts = [
  {
    Id: 0,
    Airline: "Aerolineas Argentinas",
    Origin: "Buenos Aires, Argentina",
    Destiny: "Puerto Iguazu, Misiones",
    SeatClass: "Economic",
    Baggage: "Standard",
    Price: 30000,
    Passengers: 1,
    Seats: 20,
    Img: "https://besthqwallpapers.com/Uploads/7-10-2019/107449/thumb2-colosseum-rome-morning-sunrise-flavian-amphitheatre.jpg",
  },
  {
    Id: 1,
    Airline: "Fly Bondi",
    Origin: "Cordoba, Argentina",
    Destiny: "Buenos Aires, Argentina",
    SeatClass: "Economic",
    Baggage: "Medium",
    Price: 44000,
    Passengers: 2,
    Seats: 12,
    Img: "https://wallpaperaccess.com/full/873344.jpg",
  },
  {
    Id: 2,
    Airline: "Aerolineas Argentinas",
    Origin: "Bariloche, Rio Negro",
    Destiny: "Tierra del Fuego, Argentina",
    SeatClass: "Economic",
    Baggage: "Standard",
    Price: 160000,
    Passengers: 4,
    Seats: 4,
    Img: "https://www.itl.cat/pngfile/big/199-1998569_england-london-big-ben-big-ben-wallpaper-london.jpg",
  },
];

export default mockProducts;
